package game

import (
	"encoding/binary"
	"fmt"
)

const delayedGameItemMaxCount = 32

// DelayedGameItem mirrors ITEM_FROM_SERVER plus its parallel Row/Col arrays
// in NOTIFY_DISPATCH_ITEM. The legacy name describes delayed authoritative
// production, not an inventory item owned by the account server.
type DelayedGameItem struct {
	ItemID       uint32
	DispatchTime uint32
	Row          byte
	Col          byte
}

// DispatchItemData is the schema 0x0FAE body generated by the arbitrator
// client and broadcast to every participant at battle initialization.
type DispatchItemData struct {
	Time         uint32
	Items        []GameItem
	DelayedItems []DelayedGameItem
}

func (data DispatchItemData) MarshalNetworkBinary() ([]byte, error) {
	if len(data.Items) > gameItemMaxCount {
		return nil, fmt.Errorf("NOTIFY_DISPATCH_ITEM item count %d exceeds %d", len(data.Items), gameItemMaxCount)
	}
	if len(data.DelayedItems) > delayedGameItemMaxCount {
		return nil, fmt.Errorf("NOTIFY_DISPATCH_ITEM delayed item count %d exceeds %d", len(data.DelayedItems), delayedGameItemMaxCount)
	}
	encoded := make([]byte, 0, 6+len(data.Items)*gameItemWireSize+len(data.DelayedItems)*10)
	encoded = binary.BigEndian.AppendUint32(encoded, data.Time)
	encoded = append(encoded, byte(len(data.Items)))
	for _, item := range data.Items {
		encoded = item.appendNetworkBinary(encoded)
	}
	encoded = append(encoded, byte(len(data.DelayedItems)))
	for _, item := range data.DelayedItems {
		encoded = binary.BigEndian.AppendUint32(encoded, item.ItemID)
		encoded = binary.BigEndian.AppendUint32(encoded, item.DispatchTime)
	}
	for _, item := range data.DelayedItems {
		encoded = append(encoded, item.Row)
	}
	for _, item := range data.DelayedItems {
		encoded = append(encoded, item.Col)
	}
	return encoded, nil
}

func ParseDispatchItemEvent(event GameEvent) (DispatchItemData, error) {
	if event.Schema != NotifyDispatchItem {
		return DispatchItemData{}, fmt.Errorf("dispatch-item schema 0x%04X, want 0x%04X", event.Schema, NotifyDispatchItem)
	}
	if len(event.Body) < 6 {
		return DispatchItemData{}, fmt.Errorf("NOTIFY_DISPATCH_ITEM body length %d is too short", len(event.Body))
	}
	data := DispatchItemData{Time: binary.BigEndian.Uint32(event.Body[:4])}
	itemCount := event.Body[4]
	if itemCount > gameItemMaxCount {
		return DispatchItemData{}, fmt.Errorf("NOTIFY_DISPATCH_ITEM item count %d exceeds %d", itemCount, gameItemMaxCount)
	}
	offset := 5
	itemBytes := int(itemCount) * gameItemWireSize
	if len(event.Body) < offset+itemBytes+1 {
		return DispatchItemData{}, fmt.Errorf("NOTIFY_DISPATCH_ITEM body ends inside %d ordinary items", itemCount)
	}
	items, err := parseGameItems(event.Body[offset:offset+itemBytes], itemCount)
	if err != nil {
		return DispatchItemData{}, err
	}
	data.Items = items
	offset += itemBytes
	delayedCount := event.Body[offset]
	offset++
	if delayedCount > delayedGameItemMaxCount {
		return DispatchItemData{}, fmt.Errorf("NOTIFY_DISPATCH_ITEM delayed item count %d exceeds %d", delayedCount, delayedGameItemMaxCount)
	}
	wantRemaining := int(delayedCount) * 10
	if len(event.Body)-offset != wantRemaining {
		return DispatchItemData{}, fmt.Errorf("NOTIFY_DISPATCH_ITEM delayed bytes %d, want %d for count %d", len(event.Body)-offset, wantRemaining, delayedCount)
	}
	data.DelayedItems = make([]DelayedGameItem, delayedCount)
	for index := range data.DelayedItems {
		data.DelayedItems[index].ItemID = binary.BigEndian.Uint32(event.Body[offset : offset+4])
		data.DelayedItems[index].DispatchTime = binary.BigEndian.Uint32(event.Body[offset+4 : offset+8])
		offset += 8
	}
	for index := range data.DelayedItems {
		data.DelayedItems[index].Row = event.Body[offset+index]
	}
	offset += int(delayedCount)
	for index := range data.DelayedItems {
		data.DelayedItems[index].Col = event.Body[offset+index]
	}
	return data, nil
}
